main: net.teamfekker.mobs.Main
name: TFIMobs
version: 0.3
api-version: 1.16
description: TFI MC Mobs plugin for kSMP
authors: [BearTrafalgar, GabeTrafalgar]
website: www.teamfekker.net

commands:
 tfmobs:
  description: Allows the purging of all online players.
  permission: tfmobs.reload
  usage: /tfmobs reload
 bossspawn:
  description: Spawns bosses
  permission: tfmobs.boss
  usage: /bossspawn